services:
  gateway-service:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: taskmaster_gateway
      ports:
        - "4000:4000"
      env_file:
        - ../.env
      volumes:
        - ../src:/app/src
        - ../package.json:/app/package.json
        - ../package-lock.json:/app/package-lock.json
      networks:
        - backend_network

networks:
  backend_network:
    external: true